project:
  type: website

website:
  title: "Japon 2024"
  navbar:
    left:
      - href: index.qmd
      - text: "Home"
        menu: 
          - planning.qmd
      - text: "Cartes"
        menu: 
          - carte avions.qmd
          - carte trains.qmd
      - about.qmd

format:
  html:
    page-layout: full
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

